fix upstream issue of react-quilljs
ReferenceError: require is not defined:
https://github.com/gtgalone/react-quilljs/issues/85#issuecomment-2239042095